/robot_state_publisher:
  ros__parameters:
    qos_overrides:
      '/tf':
        publisher:
          reliability: best_effort
          history: keep_last
          depth: 1

/rplidar_node:
  ros__parameters:
    qos_overrides:
      '/scan':
        publisher:
          reliability: best_effort
          history: keep_last
          depth: 1